---
- name: Download docker images
  hosts: all
  tasks:
    - name: Download omages from dockerhub
      docker_image:
        name: "{{item}}"
        source: pull
      with_items:
        - nginx
        - ghost
        - tomee
        - jenkins/jenkins
        - selenium/hub
