---
- name: installing and uninstall and upgrade s/w's
  hosts: all
  tasks:
    - name: Install/uninstall s/w's
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tree,b: present,c: no}
        - {a: openjdk-11-jdk,b: absent,c: no}
        - {a: maven,b: latest,c: yes}
...

