---
- name: configure apache/httpd based  on os
  hosts: all
  tasks:
    - name: install apache2 on ubuntu servers
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: install httpd on Rhel servers
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"
    - name: edit the index.html file
      copy:
        content: "Welcome"
        dest: /var/www/html/index.html
    - name: Restart apache2 on ubuntu servers
      service:
        name: apache2
        state: restarted
      when: ansible_distribution == "Ubuntu"
    - name: Restart httpd on RHEL servers
      service:
        name: httpd
        state: restarted
      when: ansible_distribution == "RedHat"
    - name: check apache/httpd response on all servers
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.41.201
        - http://172.31.36.84
        - http://172.31.85.217
...
