---
- name: create a file on all servers
  hosts: all
  vars:
    - a: 10
  tasks:
    - name: create a file
      file:
        name: /tmp/file10
        state: touch
        mode: 770
      when: a==10
...
