---
- name: implementing tags
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Install tree
      apt:
        name: tree
        state: present
        update_cache: yes
      tags: tree_installation
    - name: create a user
      user:
        name: Shan
        password: 123456
      tags: User_creation
    - name: copy passwd file
      copy:
        src: /etc/passwd
        dest: /tmp
...
